---
version: "3.6"

x-common-config: &common
  logging:
    driver: json-file
    options:
      tag: "{{.Name}}"
      max-size: "100m"
      max-file: "3"
  mem_limit: "512M"

networks:
  loki:
    driver: bridge

services:
  app:
    <<: *common
    image: el3os/moscow_time_python:latest
    expose:
      - 5000
    ports:
      - "5000:5000"
    networks:
      - loki

  # app2:
  #   image: el3os/moscow_time_rust
  #   ports:
  #     - "8080:5000"
  #   networks:
  #     - loki

  prometheus:
    <<: *common
    image: prom/prometheus:latest
    expose:
      - 9090
    ports:
      - "9090:9090"
    volumes:
      - ./config:/mnt/config
    command: --config.file=/mnt/config/prometheus-config.yaml
    networks:
      - loki

  loki:
    <<: *common
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./config:/mnt/config
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - loki

  promtail:
    <<: *common
    image: grafana/promtail:2.5.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./config:/mnt/config
    command: -config.file=/mnt/config/promtail-config.yaml
    networks:
      - loki

  grafana:
    <<: *common
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
