---
version: "3.6"

networks:
  loki:

services:
  app:
    image: el3os/moscow_time_python:latest
    expose:
      - 5000
    ports:
      - "5000:5000"
    networks:
      - loki

  # app2:
  #   image: el3os/moscow_time_rust
  #   ports:
  #     - "8080:5000"
  #   networks:
  #     - loki

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config:/mnt/config
    command: --config.file=/mnt/config/prometheus-config.yaml
    networks:
      - loki

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./config:/mnt/config
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./config:/mnt/config
    command: -config.file=/mnt/config/promtail-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
